# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e37ecf86e6c9d19df6e623feef775b7b3ec4e84c7696c5409087df4f30055bd93ab7d7d98d7994924e676693b8db2b02316cacc17761c068cecf5eab432141ad

test:
  secret_key_base: 777f2b69ba9d53bd37fa06a1287a04e650d9d9e7a988c3a52843a0f5b334f0978a30ccbb5ad1873dc45846b5ab156a0b8bad18deb7fab55b3c161f619bbf63c9

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
